server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://192.168.55.119:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri : lb://auth-service
#          predicates:
#            - Path = /api/v1/auth/**
#          filters:
#            - StripPrefix=0
    config:
      name: gateway
      profile: deploy
  config:
    import: "optional:configserver:http://192.168.55.119:8888/"

  main:
    allow-bean-definition-overriding: true

encrypt:
  key: ${ENCRYPT_KEY}